# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Order:
  fields:
    default: branch
    form: branch
  order_by: 
  relationships: products
  filters: created_at
  search: 
  application: brandon-app

Product:
  fields:
    default: name, stock_code, price
    form: name, stock_code, price
  order_by: 
  relationships: orders
  filters: created_at
  search: name
  application: brandon-app

